name: Run frontend tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'types/**'

jobs:
  run-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo NVMRC=`cat .nvmrc` >> $GITHUB_ENV

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NVMRC }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build frontend
        run: yarn frontend build

      - name: Run tests
        env:
          CI: true
        run: yarn frontend test
